create database TASK2;
use TASK2;
CREATE TABLE STUDENTS
(STUDENT_ID INT IDENTITY(1,1) PRIMARY KEY ,
NAME VARCHAR(20) NOT NULL,
AGE INT CHECK(AGE BETWEEN 5 AND 18) NOT NULL ,
CLASS VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL UNIQUE,
PHONE_NO BIGINT UNIQUE NOT NULL);
--CREATE TABLE TEACHERS
CREATE TABLE TEACHERS
(TEACHER_ID INT IDENTITY PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
SUBJECT VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL UNIQUE,
PHONE_NUMBER INT NOT NULL UNIQUE);
--CREATE TABLE COURSE
CREATE TABLE COURSE
(COURSE_ID INT IDENTITY PRIMARY KEY,
COURSE_NAME VARCHAR(20) NOT NULL,
TEACHER_ID INT NOT NULL,
CREDITS INT CHECK(CREDITS BETWEEN 1 AND 6),
FOREIGN KEY(TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID));
--CREATE TABLE ENROLLMENT
CREATE TABLE ENROLLMENTS
(ENROLLMENT_ID INT IDENTITY PRIMARY KEY,
STUDENT_ID INT  NOT NULL,
COURSE_ID INT  NOT NULL,
ENROLLMENT_DATE DATETIME ,
FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID));
--INSERT VALUES INTO TABLES

